name: Publish

on:
  push:
    branches:
      - v3

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt update -qy
          sudo apt-get install -y graphviz curl
      - name: Set up RVM
        run: |
          curl -sSL https://get.rvm.io | bash
      - name: Set up Ruby
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install 2.7.2 --binary
          rvm --default use 2.7.2
      - name: Install Ruby dependencies
        run: |
          source $HOME/.rvm/scripts/rvm
          bundle install
      - name: Build pages
        run: |
          source $HOME/.rvm/scripts/rvm
          bash make.sh
      - name: Publish pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          source $HOME/.rvm/scripts/rvm
          bash update_gh-pages.sh
